{
  parserClass="inc.kaizen.ui.editor.anukarma.language.AnukarmaParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Anukarma"
  psiImplClassSuffix="Impl"
  psiPackage="inc.kaizen.ui.editor.anukarma.language"
  psiImplPackage="inc.kaizen.ui.editor.anukarma.language.impl"

  elementTypeHolderClass="inc.kaizen.ui.editor.anukarma.language.IAnukarmaLanguageFileType"
  elementTypeClass="inc.kaizen.ui.editor.anukarma.language.AnukarmaElementType"
  tokenTypeClass="inc.kaizen.ui.editor.anukarma.language.AnukarmaTokenType"

  tokens=[
      EOL=";"
      SEPARATOR='='
      OPEN_BRACKET='{'
      CLOSE_BRACKET='}'
//      CRLF='regexp:\n'
//      SPACE='regexp:[ \t]+'
      LPAR='('
      RPAR=')'
      DOT='.'
      QUOTE='"'
      BOOLEAN='regexp:([Tt][Rr][Uu][Ee]|[Ff][Aa][Ll][Ss][Ee])'
      NUMBER='regexp:(\d+)'
      IDENTIFIER='regexp:(\w+)'
      GROUP_NAME='regexp:([a-zA-Z0-9_]+)'
      FILE_PATH='regexp:([a-zA-Z0-9_./\\]+.karma)'
      IMPLEMENTATION_CLASS='regexp:([a-z][a-zA-Z0-9_]*(\.[a-zA-Z0-9_]+)+[0-9A-Za-z_])'
      COMMENT='regexp:(//.*)'
      BLOCK_COMMENT='regexp:(/\*{1,2} [^*/]* \*/)'
      WHITESPACES='regexp:[\n\r\s]*'
//      SPACE='regexp:\s*'
    ]
}

anukarma ::= (PROPERTY|COMMENT|BLOCK_COMMENT|WHITESPACES|PLUGIN_SECTION|EXTENSION_SECTION|TASK_SECTION|FEATURE_SECTION)*

//WHITESPACES ::= (SPACE|CRLF)+

PROPERTY ::= (KEY WHITESPACES* SEPARATOR WHITESPACES* VALUE)
KEY ::= stopOnFail | incremental | generateCode
VALUE ::= BOOLEAN

PLUGIN_SECTION ::= plugins WHITESPACES* OPEN_BRACKET (WHITESPACES|PLUGIN_ID)* CLOSE_BRACKET
PLUGIN_ID ::= id WHITESPACES* LPAR WHITESPACES* QUOTE WHITESPACES* IDENTIFIER WHITESPACES* QUOTE WHITESPACES* RPAR

EXTENSION_SECTION ::= (extensions WHITESPACES* OPEN_BRACKET (WHITESPACES|EXTENSION_FILE)* CLOSE_BRACKET)
EXTENSION_FILE ::= (file WHITESPACES* LPAR WHITESPACES* QUOTE WHITESPACES* FILE_PATH WHITESPACES* QUOTE WHITESPACES* RPAR)

TASK_SECTION ::= (task WHITESPACES* LPAR WHITESPACES* QUOTE WHITESPACES* IDENTIFIER WHITESPACES* QUOTE WHITESPACES* RPAR WHITESPACES* OPEN_BRACKET (WHITESPACES|COMMENT|BLOCK_COMMENT|TASK_PROPERTIES)* CLOSE_BRACKET)
TASK_PROPERTIES ::= TASK_PROPERTY_IMPLEMENTATION | TASK_PROPERTY_GROUP | TASK_PROPERTY_STRICT_DEPENDENCY | TASK_DEPENDENCY
TASK_PROPERTY_IMPLEMENTATION ::= (implementation WHITESPACES* SEPARATOR WHITESPACES* QUOTE WHITESPACES* IMPLEMENTATION_CLASS WHITESPACES* QUOTE)
TASK_PROPERTY_GROUP ::= (group WHITESPACES* SEPARATOR WHITESPACES* QUOTE WHITESPACES* IDENTIFIER WHITESPACES* QUOTE)
TASK_PROPERTY_STRICT_DEPENDENCY ::= (strictDependency WHITESPACES* SEPARATOR WHITESPACES* BOOLEAN)
TASK_DEPENDENCY ::= dependsOn WHITESPACES* OPEN_BRACKET (WHITESPACES|TASK_DEPENDENCY_ID)* CLOSE_BRACKET
TASK_DEPENDENCY_ID ::= id WHITESPACES* LPAR WHITESPACES* QUOTE WHITESPACES* IDENTIFIER WHITESPACES* QUOTE WHITESPACES* RPAR

FEATURE_SECTION ::= feature WHITESPACES* LPAR WHITESPACES* QUOTE WHITESPACES* IDENTIFIER WHITESPACES* QUOTE WHITESPACES* RPAR WHITESPACES* OPEN_BRACKET (WHITESPACES|COMMENT|BLOCK_COMMENT|FEATURE_PROPERTIES|FEATURE_DEPENDENCY|TASK_SECTION)* CLOSE_BRACKET
FEATURE_PROPERTIES ::= FEATURE_PROPERTY_PRIORITY
FEATURE_PROPERTY_PRIORITY ::= (priority WHITESPACES* SEPARATOR WHITESPACES* NUMBER)
FEATURE_DEPENDENCY ::= dependsOn WHITESPACES* OPEN_BRACKET (WHITESPACES|FEATURE_DEPENDENCY_ID)* CLOSE_BRACKET
FEATURE_DEPENDENCY_ID ::= id WHITESPACES* LPAR WHITESPACES* QUOTE WHITESPACES* IDENTIFIER WHITESPACES* QUOTE WHITESPACES* RPAR